### ISSUE TITLE
see only logo in main page

### ISSUE THREAD

**Issue by changchichung** [FormPress/FormPress#2]
after running docker-compose up -d
there's only a logo shown on the page
![](http://ny.cowbay.org:40115/opera_vNLV0WqvMJ.png/direct)

docker compose logs -f

```
mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
formpress-mysql     | 2024-01-26T04:25:39.837363Z 0 [Note] Event Scheduler: Loaded 0 events
formpress-mysql     | 2024-01-26T04:25:39.837582Z 0 [Note] mysqld: ready for connections.
formpress-mysql     | Version: '5.7.44'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
formpress-mysql     | 2024-01-26T04:25:43.442024Z 4 [Note] Aborted connection 4 to db: 'formpress' user: 'formpress' host: '172.29.0.3' (Got an error reading communication packets)
```

any suggestions ?

**Comment by kemaldaggen** [comment]
Hi @changchichung 

Can you tell us more information about your system? What is your OS and version and what is your currently installed Docker version?

**Comment by changchichung** [comment]
>> What is your OS 
 
ubuntu 22.04

>> docker version 

```
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

formpress-frontend logs
```
 docker logs formpress-frontend
yarn run v1.22.19
$ NODE_PATH=/node_modules react-scripts start
(node:43) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:43) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view frontend in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://172.31.0.4:3000

Note that the development build is not optimized.
To create a production build, use yarn build.

webpack compiled successfully
```
backend logs
```
Transpiling /frontend/src/modules/internal/List.js
Returning file(List.js) from cache
Transpiling /frontend/src/modules/internal/NumberE.js
Returning file(NumberE.js) from cache
Transpiling /frontend/src/modules/internal/Password.js
Returning file(Password.js) from cache
Transpiling /frontend/src/modules/internal/index.js
Returning file(index.js) from cache
Transpiling /frontend/src/modules/internal/List.css
Transpiling /frontend/src/modules/internal/NumberE.css
Transpiling /frontend/src/modules/internal/Password.css
Transforming files took 0.076 seconds
reCAPTCHA is not initialized. Reason: missing env variables.
(node:78) Warning: Accessing non-existent property 'error' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Example app listening on port 3001!
```

mysql logs
```
2024-01-30T08:24:16.026894Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2024-01-30T08:24:16.026995Z 0 [Note] IPv6 is available.
2024-01-30T08:24:16.027357Z 0 [Note]   - '::' resolves to '::';
2024-01-30T08:24:16.027450Z 0 [Note] Server socket created on IP: '::'.
2024-01-30T08:24:16.031245Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2024-01-30T08:24:16.041566Z 0 [Note] Event Scheduler: Loaded 0 events
2024-01-30T08:24:16.041840Z 0 [Note] mysqld: ready for connections.
Version: '5.7.44'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
2024-01-30T08:24:19.084886Z 4 [Note] Aborted connection 4 to db: 'formpress' user: 'formpress' host: '172.31.0.3' (Got an error reading communication packets)
```

**Comment by kemaldaggen** [comment]
thanks for the feedback @changchichung 

I've updated the documentation.

For now you can simply do following to fix your issues after pulling.

First make sure you've destroyed any previously created database by simply running

```
docker compose down
docker compose up
```

Then create .env file

```
cp .env.example .env
```

Then start services

```
docker compose up
```

You should be able to login with below default credentials
```
username: admin@example.com
password: CHANGEME
```

Let us know if you spot any more issues. 

For full functionality, some more configuration is needed as FormPress is an application that utilizes several other services. To name a few, we use Google Storage Buckets for file uploads and SendGrid for emails.

**Comment by changchichung** [comment]
so , I delete the old one , then git clone again , run docker compose up 
and there's an error 
```
Uncaught runtime errors:
×
ERROR
Failed to fetch
TypeError: Failed to fetch
    at http://192.168.100.2:3000/static/js/bundle.js:1605:3
    at new Promise (<anonymous>)
    at api (http://192.168.100.2:3000/static/js/bundle.js:1589:7)
    at App.whoAmI (http://192.168.100.2:3000/static/js/bundle.js:225:62)
    at App.componentDidMount (http://192.168.100.2:3000/static/js/bundle.js:301:16)
```
full log here

https://paste.fo/61af4e81809e

**Comment by kemaldaggen** [comment]
Interesting,

Can you try accessing via http://localhost:3000

and check if backend process is running?

**Comment by changchichung** [comment]
there's no desktop environment in the docker host , I can not run web browser to check.

any other suggestions ?
